apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: two
    app.kubernetes.io/version: 0.1.0
  name: two-service
  namespace: two
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app.kubernetes.io/name: two
  type: ClusterIP
