apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - namespace.yaml
  - service.yaml

configMapGenerator:
- envs:
  - one.properties
  name: one-configmap

labels:
- includeSelectors: true
  pairs:
    override/namespace: kube-system

transformers:
  - cluster-name-transformer.yaml
