apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: one
    app.kubernetes.io/version: 0.1.0
  name: one-service
  namespace: one
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app.kubernetes.io/name: one
  type: ClusterIP
